baseURL = 'https://talkingrock.ai/'
languageCode = 'en-us'
title = 'Talking Rock AI'

[params]
  description = 'Local, zero trust AI. Small models and footprint, outsized impact and trust.'
  tagline = 'Center your data around you,<br>not a data center.'

[menus]
  [[menus.main]]
    name = 'Cairn'
    url = '/cairn/'
    weight = 1
  [[menus.main]]
    name = 'ReOS'
    url = '/reos/'
    weight = 2
  [[menus.main]]
    name = 'RIVA'
    url = '/riva/'
    weight = 3
  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 4
  [[menus.main]]
    name = 'Blog'
    url = 'https://rogueroutine.substack.com'
    weight = 5
    [menus.main.params]
      external = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true

[minify]
  minifyOutput = false
