baseURL = 'https://talkingrock.ai/'
languageCode = 'en-us'
title = 'Talking Rock AI'

[params]
  description = 'Local, zero trust AI. Small models and footprint, outsized impact and trust.'
  tagline = 'Center your data around you,<br>not a data center.'

[menus]
  [[menus.main]]
    name = 'CAIRN'
    url = '/cairn/'
    weight = 1
  [[menus.main]]
    name = 'Demo'
    url = '/demo/'
    weight = 2
  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 3
  [[menus.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true

[minify]
  minifyOutput = false
